apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: docker.io/manisomanish/gitops:40
          name: nginx
#           resources:
#             requests:
#               memory: "20Gi"
#               cpu: "2k"
#             limits:
#               memory: "20Gi"
#               cpu: "2k"
  
