apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-v2
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx-v2
    spec:
      containers:
        - image: docker.io/manisomanish/gitops:40
          name: nginx-v2
          resources:
            requests:
              memory: "1Gi"
              cpu: "1k"
            limits:
              memory: "1Gi"
              cpu: "1k"
  
